name: 'Continuous Integration'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
        
    - name: Install Dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt -r requirements-test.txt -r requirements-dev.txt
        pip install fastapi uvicorn anyio "starlette==0.20.4"

    - name: Run Model Tests
      run: make model-test

    - name: Run API Tests
      run: make api-test
